# Generated by Django 4.1.5 on 2023-01-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_request_food_request_cleaning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_cleaning',
            name='cleaning',
        ),
        migrations.RemoveField(
            model_name='request_food',
            name='food',
        ),
        migrations.AddField(
            model_name='request_cleaning',
            name='cleaning',
            field=models.ManyToManyField(to='products.cleaning'),
        ),
        migrations.AddField(
            model_name='request_food',
            name='food',
            field=models.ManyToManyField(to='products.food'),
        ),
    ]
