# Generated by Django 4.1.5 on 2023-01-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_request_cleaning_cleaning_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='type',
            new_name='typeCategoria',
        ),
    ]
