# Generated by Django 4.1.5 on 2023-01-20 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_request_cleaning_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_cleaning',
            name='cleaning',
        ),
        migrations.RemoveField(
            model_name='request_cleaning',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='request_food',
            name='food',
        ),
        migrations.RemoveField(
            model_name='request_food',
            name='quantity',
        ),
        migrations.AddField(
            model_name='request_cleaning',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request_food',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Food_RequestFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.food')),
                ('requestfood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.request_food')),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning_RequestCleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('cleaning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cleaning')),
                ('requestcleaning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.request_cleaning')),
            ],
        ),
    ]
