import os
import time
from time import sleep
from selenium import webdriver
from django.test import TestCase
from selenium.webdriver.common.by import By
from utils.browser import make_chrome_browser
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from django.contrib.staticfiles.testing import StaticLiveServerTestCase

class FunctionalTestsDocuments(TestCase, StaticLiveServerTestCase):
    def test_memorando_list_page_form_page_detail_page_and_report_page(self):
        
        browser = make_chrome_browser()
        browser.get(self.live_server_url)
        browser.maximize_window()
        wait = WebDriverWait(browser, 10)
        sleep(1)
        log = browser.find_element(By.ID, 'log')
        log.click()
        sleep(1)
        register = browser.find_element(By.ID, 'register')
        register.click()
        username = browser.find_element(By.NAME, "username")
        username.send_keys("TesteSelenium2")
        sleep(1)
        email = browser.find_element(By.NAME, "email")
        email.send_keys("Sselenium2@gmail.com")
        sleep(2)
        typeUser = wait.until(EC.presence_of_element_located((By.XPATH, '//select[@class="form-control select"]')))
        select = Select(typeUser)
        select.select_by_value('secretary')
        sleep(1)
        password1 = browser.find_element(By.NAME, "password1")
        password1.send_keys("sel12345.")
        sleep(1)
        password2 = browser.find_element(By.NAME, "password2")
        password2.send_keys("sel12345.")
        password2.send_keys(Keys.RETURN)
        sleep(2)
        username = browser.find_element(By.NAME,"username")
        username.clear()
        username.send_keys("Sselenium2@gmail.com")
        sleep(1)
        password = browser.find_element(By.NAME, "password")
        password.send_keys("sel12345.")
        password.send_keys(Keys.RETURN)
        sleep(2)
        hbg = wait.until(EC.presence_of_element_located((By.ID, 'hamburguer')))
        hbg.click()
        sleep(2)
        docs = browser.find_element(By.ID, "documents")
        docs.click()
        sleep(1)
        memo = browser.find_element(By.ID, "memorando")
        memo.click()
        sleep(1)
        btnmemo = browser.find_element(By.ID, "btnmemorando")
        btnmemo.click()
        sleep(2)
        destiny = browser.find_element(By.NAME, "destiny")
        select2 = Select(destiny)
        select2.select_by_visible_text("Secretaria de Obras")
        sleep(1)
        outro = browser.find_element(By.NAME, "others")
        outro.send_keys('kkkk')
        sleep(1)
        dest = browser.find_element(By.NAME, "receiver")
        dest.send_keys('José da Vida')
        sleep(1)
        title = browser.find_element(By.NAME, "title")
        title.send_keys('Teste selenium')
        sleep(1)
        description = browser.find_element(By.NAME, "description")
        description.send_keys('Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium ')
        sleep(1)
        btnSaveMemorando = browser.find_element(By.ID, "btnSaveMemorando")
        browser.execute_script("arguments[0].click()", btnSaveMemorando)
        sleep(1)
        memorandoDetail = browser.find_element(By.ID, "memorandoDetail")
        browser.execute_script("arguments[0].click()", memorandoDetail)
        sleep(1)
        aprovar = browser.find_element(By.ID, "aprovar")
        browser.execute_script("arguments[0].click()", aprovar)
        sleep(1)
        memorandoDetail2 = browser.find_element(By.ID, "memorandoDetail")
        browser.execute_script("arguments[0].click()", memorandoDetail2)
        sleep(1)
        verificar = browser.find_element(By.ID, "verificar")
        browser.execute_script("arguments[0].click()", verificar)
        sleep(3)
        assert "Print Memorando" in browser.title
        browser.quit()
        
    def test_official_list_page_form_page_detail_page_and_report_page(self):
        
        browser = make_chrome_browser()
        browser.get(self.live_server_url)
        browser.maximize_window()
        wait = WebDriverWait(browser, 10)
        sleep(1)
        log = browser.find_element(By.ID, 'log')
        log.click()
        sleep(1)
        register = browser.find_element(By.ID, 'register')
        register.click()
        username = browser.find_element(By.NAME, "username")
        username.send_keys("TesteSelenium2")
        sleep(1)
        email = browser.find_element(By.NAME, "email")
        email.send_keys("Sselenium2@gmail.com")
        sleep(2)
        typeUser = wait.until(EC.presence_of_element_located((By.XPATH, '//select[@class="form-control select"]')))
        select = Select(typeUser)
        select.select_by_value('secretary')
        sleep(1)
        password1 = browser.find_element(By.NAME, "password1")
        password1.send_keys("sel12345.")
        sleep(1)
        password2 = browser.find_element(By.NAME, "password2")
        password2.send_keys("sel12345.")
        password2.send_keys(Keys.RETURN)
        sleep(2)
        username = browser.find_element(By.NAME,"username")
        username.clear()
        username.send_keys("Sselenium2@gmail.com")
        sleep(1)
        password = browser.find_element(By.NAME, "password")
        password.send_keys("sel12345.")
        password.send_keys(Keys.RETURN)
        sleep(2)
        hbg = wait.until(EC.presence_of_element_located((By.ID, 'hamburguer')))
        hbg.click()
        sleep(2)
        docs = browser.find_element(By.ID, "documents")
        docs.click()
        sleep(1)
        memo = browser.find_element(By.ID, "officio")
        memo.click()
        sleep(1)
        btnmemo = browser.find_element(By.ID, "addOfficial")
        btnmemo.click()
        sleep(2)
        destiny = browser.find_element(By.NAME, "destiny")
        select2 = Select(destiny)
        select2.select_by_visible_text("Secretaria de Obras")
        sleep(1)
        outro = browser.find_element(By.NAME, "others")
        outro.send_keys('official')
        sleep(1)
        dest = browser.find_element(By.NAME, "receiver")
        dest.send_keys('José do oficio')
        sleep(1)
        description = browser.find_element(By.NAME, "description")
        description.send_keys('Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium ')
        sleep(1)
        btnofficial = browser.find_element(By.ID, "btnofficial")
        browser.execute_script("arguments[0].click()", btnofficial)
        sleep(1)
        detailOfficial = browser.find_element(By.ID, "detailOfficial")
        browser.execute_script("arguments[0].click()", detailOfficial)
        sleep(1)
        aprovar = browser.find_element(By.ID, "aprovar")
        browser.execute_script("arguments[0].click()", aprovar)
        sleep(1)
        detailOfficial2 = browser.find_element(By.ID, "detailOfficial")
        browser.execute_script("arguments[0].click()", detailOfficial2)
        sleep(1)
        imprimirOfficial = browser.find_element(By.ID, "imprimirOfficial")
        browser.execute_script("arguments[0].click()", imprimirOfficial)
        sleep(3)
        assert "Print Official" in browser.title
        browser.quit()
        
    def test_request_list_page_form_page_detail_page_and_report_page(self):
        
        browser = make_chrome_browser()
        browser.get(self.live_server_url)
        browser.maximize_window()
        wait = WebDriverWait(browser, 10)
        sleep(1)
        log = browser.find_element(By.ID, 'log')
        log.click()
        sleep(1)
        register = browser.find_element(By.ID, 'register')
        register.click()
        username = browser.find_element(By.NAME, "username")
        username.send_keys("TesteSelenium2")
        sleep(1)
        email = browser.find_element(By.NAME, "email")
        email.send_keys("Sselenium2@gmail.com")
        sleep(2)
        typeUser = wait.until(EC.presence_of_element_located((By.XPATH, '//select[@class="form-control select"]')))
        select = Select(typeUser)
        select.select_by_value('secretary')
        sleep(1)
        password1 = browser.find_element(By.NAME, "password1")
        password1.send_keys("sel12345.")
        sleep(1)
        password2 = browser.find_element(By.NAME, "password2")
        password2.send_keys("sel12345.")
        password2.send_keys(Keys.RETURN)
        sleep(2)
        username = browser.find_element(By.NAME,"username")
        username.clear()
        username.send_keys("Sselenium2@gmail.com")
        sleep(1)
        password = browser.find_element(By.NAME, "password")
        password.send_keys("sel12345.")
        password.send_keys(Keys.RETURN)
        sleep(2)
        hbg = wait.until(EC.presence_of_element_located((By.ID, 'hamburguer')))
        hbg.click()
        sleep(2)
        docs = browser.find_element(By.ID, "documents")
        docs.click()
        sleep(1)
        req = browser.find_element(By.ID, "requirements")
        req.click()
        sleep(1)
        btnreq = browser.find_element(By.ID, "addRequeriment")
        btnreq.click()
        sleep(2)
        destiny = browser.find_element(By.NAME, "destiny")
        select2 = Select(destiny)
        select2.select_by_visible_text("Secretaria de Obras")
        sleep(1)
        outro = browser.find_element(By.NAME, "others")
        outro.send_keys('requirements')
        sleep(1)
        dest = browser.find_element(By.NAME, "receiver")
        dest.send_keys('José do Requerimento')
        sleep(1)
        description = browser.find_element(By.NAME, "description")
        description.send_keys('Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium Teste selenium ')
        sleep(1)
        btnSaveRequeriment = browser.find_element(By.ID, "btnSaveRequeriment")
        browser.execute_script("arguments[0].click()", btnSaveRequeriment)
        sleep(1)
        requirementDetail = browser.find_element(By.ID, "requirementDetail")
        browser.execute_script("arguments[0].click()", requirementDetail)
        sleep(1)
        aprovar = browser.find_element(By.ID, "aprovar")
        browser.execute_script("arguments[0].click()", aprovar)
        sleep(1)
        requirementDetail2 = browser.find_element(By.ID, "requirementDetail")
        browser.execute_script("arguments[0].click()", requirementDetail2)
        sleep(1)
        imprimir = browser.find_element(By.ID, "imprimir")
        browser.execute_script("arguments[0].click()", imprimir)
        sleep(3)
        assert "Print Requeriment" in browser.title
        browser.quit()