# Generated by Django 4.1.5 on 2023-01-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food_event',
            name='name',
        ),
    ]
