# Generated by Django 4.1.5 on 2023-02-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorando',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='official',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='requeriment',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='memorando',
            name='destiny',
            field=models.CharField(choices=[('Secretaria de Planejamento', 'Secretaria de Planejamento'), ('Secretaria de Obras', 'Secretaria de Obras'), ('Secretaria de Finanças', 'Secretaria de Finanças'), ('Gabinete do Prefeito', 'Gabinete do Prefeito'), ('Camâra de Vereadores', 'Camâra de Vereadores'), ('Secretaria de Educação', 'Secretaria de Educação'), ('Outros', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='official',
            name='destiny',
            field=models.CharField(choices=[('Secretaria de Planejamento', 'Secretaria de Planejamento'), ('Secretaria de Obras', 'Secretaria de Obras'), ('Secretaria de Finanças', 'Secretaria de Finanças'), ('Gabinete do Prefeito', 'Gabinete do Prefeito'), ('Camâra de Vereadores', 'Camâra de Vereadores'), ('Secretaria de Educação', 'Secretaria de Educação'), ('Outros', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='requeriment',
            name='destiny',
            field=models.CharField(choices=[('Secretaria de Planejamento', 'Secretaria de Planejamento'), ('Secretaria de Obras', 'Secretaria de Obras'), ('Secretaria de Finanças', 'Secretaria de Finanças'), ('Gabinete do Prefeito', 'Gabinete do Prefeito'), ('Camâra de Vereadores', 'Camâra de Vereadores'), ('Secretaria de Educação', 'Secretaria de Educação'), ('Outros', 'Outros')], max_length=50),
        ),
    ]
