# Generated by Django 4.1.5 on 2023-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_typeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typeUser',
            field=models.CharField(blank=True, choices=[('secretary', 'Secretary'), ('asg', 'Asg'), ('coordinator', 'Coordinator'), ('nutricionist', 'Nutricionist'), ('food_divider', 'Food Divider')], max_length=20, null=True),
        ),
    ]
