# Generated by Django 4.1.5 on 2023-02-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typeUser',
            field=models.CharField(blank=True, choices=[('secretary', 'Secretary'), ('asg', 'Asg'), ('coordinator', 'Coordinator'), ('nutricionist', 'Nutricionist'), ('fooddivider', 'Food Divider')], max_length=20, null=True),
        ),
    ]
